### ISSUE TITLE
UnicodeEncodeError with toolsmanager.py

### ISSUE THREAD

**Issue by gabanz** [PentestBox/tracker#105]
Tool which is causing the issue: toolsmanager.py
System Architecture: 64-bit

     Name                                                 Description
Traceback (most recent call last):
  File "C:\PentestBox\bin\scripts\toolsmanager.py", line 286, in <module>
    welcome()
  File "C:\PentestBox\bin\scripts\toolsmanager.py", line 55, in welcome
    parse_tools("/modules/android")
  File "C:\PentestBox\bin\scripts\toolsmanager.py", line 155, in parse_tools
    print (table_short.table)
UnicodeEncodeError: 'cp932' codec can't encode character u'\u2554' in position 0: illegal multibyte sequence

**Comment by ghost** [comment]
I just got the same problem. Then I change the 'cp932' with type 'chcp 437' and it's work for me.
